apiVersion: v2
name: lowcoder
description: A Helm chart for Kubernetes for installing lowcoder

type: application
# Chart version (change every time you make changes to the chart)
version: 2.6.6

# Lowcoder version
appVersion: "2.6.6"

# Dependencies needed for Lowcoder deployment
dependencies:
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 19.1.0
  - condition: mongodb.enabled
    name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.1.4

